corpus <- c("n417", "disturbance", "grand theft auto", "assault", "burglary", 
            "vandalism", "atmt to locate", "drug arrest", "traffic stop", 
            "larceny", "graffiti complaint / reporting", "burglary", "narcotics inside", 
            "disturbance - priority", "investigate person", "proactive police visit", 
            "disorderly", "theft", "agency assist", "cad: suspicious activity", 
            "criminal trespass", "dop nrs", "unknown problem", "traffic signal trouble", 
            "-arrest on warrant", "traffic", "cad: suspicious activity", 
            "burglary", "traffic stop-si so", "drug poss", "larceny", "theft from vehicle", 
            "burg vehic", "forgery", "burglary information     ", "assault, aggravated", 
            "animal complaint - livability", "all other offense", "assault a", 
            "[rms] larceny", "406v", "criminal mischief", "domestic disturbance", 
            "[inc] burglary to a vehicle", "traffic stop", "drug poss", "traffic stop-si kp", 
            "larceny", "vehicle-abandoned/disabled", "unwanted", "premise check", 
            "disorderly", "grand larc", "burglary", "hit & run motor vehicle accident", 
            "other", "larceny", "other", "theft from vehicle", "larceny", 
            "larceny", "stealing", "drug overdose", "larceny, watercraft", 
            "traffic", "disturbance", "assist", "other", "special attention", 
            "accident", "petit larc", "ts", "grand larc", "larceny", "arr theft-ms-shoplifting-500 or less", 
            "lab request", "sick case", "petty theft [pc 484(a)]", "045 - assault - intimidation,threats/harassment", 
            "community policing", "gta - recovery", "burglary/force/res/am", 
            "disorderly conduct", "intimidate", "theft from vehicle - petty", 
            "[wpd]-23d", "disturbance (other)", "abandoned vehicle", "theft of motor vehicle parts or accessories", 
            "assault, simple", "407", "disturbance", "motor vehicle theft", 
            "citizen dispute", "burgr", "[cad]area patrol bus 17b", "dui", 
            "phone harassment", "dist the peace", "fraud", "drugs", "*traffic stop", 
            "all other offenses", "cad: vehicle theft", "proactive police visit", 
            "drug poss", "auto x hit& run unk injuries", "drug poss", "fraud, other(old)", 
            "alc - alarm commercial", "graffiti complaint / reporting", "petit larc", 
            "larceny theft", "[ta] traffic accident", "290 - destruction/damage/vandalism of property", 
            "lost prop     ", "larceny", "abandoned vehicle", "theft from auto", 
            "vehicle break-in/theft", "larceny", "nat traffic stop", "missing serious", 
            "disorderly", "missing serious", "[cad] traff-s", "drugs/alcohol violations", 
            "pc 451 arson", "assault/knife", "81a", "malicious destruction i/p", 
            "416b", "remarks", "assault and battery", "felonious assault ip", 
            "motor vehicle theft", "theft-property-other", "traffic illinois vehicle code", 
            "wi 5150 mental disorder", "traffic signal trouble", "harassment (no physical contact)", 
            "ts", "theft", "traffic stop", "assault, aggravated", "hit & run", 
            "fraud", "motor vehicle collision investigation", "accident, traffic - in house", 
            "sewer issues", "citizen dispute", "weapons concealed", "runaway", 
            "larceny auto parts/accessories", "ibr 35a drug/narcotic violations", 
            "crim trespass", "fraud-other", "har - harrassment", "common assault", 
            "cfs-watch order", "assault and battery", "suspicious", "business/building check", 
            "traffic stop", "missing person", "911/no  voice", "911 hangup", 
            "non-aggravated assaults", "cps referral", "found property", 
            "traffic stop", "1801", "traff acc", "agency assist", "all other non-traffic crim offenses", 
            "90f family offenses, nonviolent", "pothole", "alarm", "90z all other offenses", 
            "reports: missing person", "parking violation complaint", "complaint other", 
            "investigate person", "exterior nuisance complaint", "burgr", 
            "vehicle stop", "cfs-traffic stop", "13(a)(31)", "traffic stop", 
            "[cad]-reckless driving", "traffic", "[inc] tstop", "property-found", 
            "robbery/knife/residence", "medical", "suspicious circ", "larceny", 
            "alarm unknown cause", "gta", "narco (not marijuana)", "vehicle stop", 
            "auto or ped h&r report", "larceny", "traffic stop", "auto x unk inj / impaired", 
            "403a assault - other dangerous weapon", "runaway", "larceny f/auto", 
            "missing report", "trespassing", "parking violation complaint", 
            "traffic", "traffic", "animal complaint - livability", "[cad] accident (no injuries)", 
            "false alarms", "graffiti complaint / reporting", "special detail", 
            "burglary (residential)", "bomb", "larceny theft", "missing person", 
            "traffic", "larceny", "sidewalk snow & ice complaint", "assault in progress", 
            "416b", "alarm - business", "aps referral", "towing detail", 
            "dui", "burg of veh-loose items only", "911/no  voice", "13b - simple assault", 
            "missing serious", "petit larc", "vicious animal", "bus boarding", 
            "drug arrest", "6/10/2017 1:17:00 am", "motor vehicle theft", 
            "property crime", "theft", "animal complaint - livability", "death", 
            "family disturb", "parking violation complaint", "prowler", "runaway", 
            "security check", "theft", "larceny", "disturbance", "burglary vehicle", 
            "[049] suspicious person", "traff acc", "theft - commercial", 
            "battery a", "[cad] susp-v", "petty theft / theft of personal property / shoplift", 
            "traff acc", "abandoned vehicle", "community policing", "larceny, shoplifting", 
            "graffiti complaint / reporting", "theft from auto", "larceny", 
            "rms battery; causing bodily harm", "911w/hu", "gta", "10-95", 
            "business/building check", "cit speeding - school zone", "911/no  voice", 
            "one down or over the wheel", "larceny", "theft from vehicle", 
            "business check", "harrassment/threat/attempt/phy", "[ccso]- building, parking lot check", 
            "mt ems-tro/entry", "accident", "all other offenses", "property found", 
            "[cad] traffic stop", "unknown problem", "rms: under $50 theft/shoplifting", 
            "lost property", "traffic stop", "one down or over the wheel", 
            "[ccso] animal problem", "larceny", "burglary", "traffic stop", 
            "simple criminal damage", "[rms] traf-moving traffic viola", 
            "dui", "grand theft auto", "[cad]-business-check", "911 call", 
            "rape ip or jh", "burglary", "sc: medical assist", "larceny - theft from a motor vehicle", 
            "[inc] domestic trouble/domestic dispute", "traffic", "burglary", 
            "traff acc", "silent alarm", "welfare check - priority", "xcad disabled vehicle", 
            "cad: none", "towing detail", "406", "check person", "remarks", 
            "[rms] vehicle theft", "trf-hitrun", "traffic stop", "animal complaint - public health", 
            "traffic enforce", "chk well being", "larceny", "06", "other assaults", 
            "80b", "prkg complaint", "[rms] pub peace-mentally ill subj", 
            "runaway", "bus boarding", "4203", "burglary", "11-95", "traff acc", 
            "missing person", "abandoned vehicle", "service call", "grand larc", 
            "traff acc", "2633", "suspicious vehicle", "n406", "inci: atc - attempt to contact/locate", 
            "verified alr / person w/o code", "stolen vehicle", "assault, simple", 
            "larceny", "alarm call commercial", "malicious destruction i/p", 
            "auto thefts", "fel. assault", "found property", "traffic stop", 
            "assault, simple", "disorderly", "drug poss", "arr theft-gm-by swindle or trick-501-1000", 
            "90d driving under the influence", "traffic stop", "larceny", 
            "runaway", "condition of release violation", "theft -(motor vehicle)", 
            "traffic stop", "alarm", "traffic stop", "suspicious incident", 
            "business check", "dui", "found property", "assault with injury     ", 
            "narcotics", "noise complaint", "community policing", "other", 
            "sex offender registration check", "citizen assist", "special attention", 
            "traffic stop", "disturbance", "repo", "stln prop", "false burglar alarm", 
            "drug poss", "animal complaint - public health", "traffic stop", 
            "drug poss", "disturbance", "all other offenses", "special attention", 
            "deceptive practice", "family disturb", "disorderly conduct", 
            "assault and battery report", "verified alr / person w/o code", 
            "missing serious", "other", "traffic", "shoplifting", "33 - theft", 
            "robbery", "shooting/cutting/pent wnd rpt", "51c", "n416a", "felonious assault ip", 
            "property crime", "investigate auto", "suspicious subj, veh, or circumstance", 
            "veh recstl", "hpd-traffic - vehicle tow / storage", "13b - simple assault", 
            "animal complaint - public health", "other", "drugs", "traffic stop", 
            "vehicle stop", "exterior nuisance complaint", "reports: citizen assist", 
            "traffic stop", "[ccso]- 10 58 traffic stop", "complaint other", 
            "[cad] traff-s", "traffic stop", "remarks", "larceny", "abandoned vehicle", 
            "common assault", "suspicious person", "abandoned vehicle", "animal complaint", 
            "suspicious person", "inci: bx-building check", "runaway", "assault", 
            "cad: suspicious activity", "harrassment", "traff acc", "special attention", 
            "narcoticsoutside", "prostitution", "[rms] larceny", "unknown trouble", 
            "selective traffic enforcement", "accident", "tamper mv", "larceny", 
            "crim mis misd", "shot stabbed unk or obv death", "publicinto", 
            "child / adult abuse report", "traffic", "other sexual offense", 
            "motor veh crash", "sidewalk snow & ice complaint", "larceny", 
            "[cit] interstate highway regulations", "criminal damage", "narcoticsoutside", 
            "general assistance (escorts, service calls)", "ptchp", "lost property", 
            "[ccso]- building, parking lot check", "alarm", "assault, aggravated", 
            "graffiti", "found property", "theft", "motor vehicle theft/auto", 
            "disorderly", "[cad]-traffic stop", "[cit] interstate highway regulations", 
            "35c", "traffic stop", "fraud and nsf checks", "larceny", "other assaults", 
            "complaint other", "larceny", "false burglar alarm", "traff acc", 
            "fraud report", "subj with gun", "udaa report", "traffic", "burg vehic", 
            "welfare check - cold", "battery", "larceny", "rms: accident property damage", 
            "community policing", "anc - animal complaint", "repo", "416b", 
            "605c theft \\ burglary from veh - motor vehicle parts and acc.", 
            "animal complaint - livability", "[lcpd] noise problem", "[rms] dwi", 
            "traffic stop", "narcotics", "miscellaneous", "fraud", "grand larc", 
            "theft", "towing detail", "xcad alarm burglar", "vehicle-towed/stored", 
            "grand theft auto", "community policing", "larceny - from motor vehicle(not 21", 
            "auto x unk inj / impaired", "directed patrol", "animal complaint - livability", 
            "[gpd]-traffic", "290 - destruction/damage/vandalism of property", 
            "family disturbance", "narcoticsoutside", "burgv", "drug poss", 
            "theft/larc/0-50/veh parts", "ts", "cad: suspicious activity", 
            "xcad warrant service", "burglary occupied resd i/p", "dui", 
            "larceny i/p or j/h", "follow up", "fight", "robbery", "recovered veh", 
            "towing detail", "06057-predpol check", "cad: traffic stop", 
            "traffic stop", "assault and battery", "assault in progress", 
            "theft/other", "[ccso]- building, parking lot check", "special attention", 
            "disorderly", "verified alr / person w/o code", "civil standby", 
            "emergency", "[rms] terroristic threat family", "theft-vehicle", 
            "drug arrest", "911/no  voice", "burglary", "vehicle check", 
            "aggravated assault", "community policing", "auto or ped h&r report", 
            "community policing", "community policing", "petit larc", "disord conduct", 
            "larceny f/auto", "90z - warrant arrest-ppd", "dui", "other", 
            "[cfs] traffic", "threats report", "drug sales", "911/no  voice", 
            "reckless driver", "narcoticsoutside", "939i misconduct - disturbing the peace", 
            "animal complaint", "411", "traffic stop", "repairs/service", 
            "driving under the influence", "traffic stop", "drug poss", "fraud", 
            "motor vehicle theft", "theft of vehicle", "5505", "theft", "rubbish littering i/p", 
            "breaking and entering", "community policing", "10-50 traffic stop", 
            "motor vehicle theft", "residential conditions complaint", "exp", 
            "suspicious person", "drug arrest", "disturbance", "pedestrian stop", 
            "larceny", "robbery", "vandalism", "repo", "larceny", "common assault", 
            "drug arrest", "[rms] harassment", "vandalism [$400 or less] (m)", 
            "person with weapon", "[cfs] traffic", "drug poss", "premise check", 
            "burglary", "47", "traffic stop", "- larceny-articles from vehicle [2305]", 
            "audible alarm residential", "traffic", "traffic stop", "assault and battery", 
            "publicinto", "theft-shoplift", "cfs-area check", "burglary", 
            "911/no  voice", "1311", "disturbance", "6187 theft +$201 from building", 
            "vandalism", "cheyenne court apartments", "serving search warrant", 
            "robbery no firearm", "ckw - check on the welfare", "larceny", 
            "withhold support-non support of children or spouse", "dui", 
            "parking problem", "assault and battery", "scrap strip  bldg  ip", 
            "unknown problem", "thefts", "motor vehicle theft", "larceny other over $200", 
            "450 - robbery", "check wellbeing", "unknown problem", "graffiti complaint / reporting", 
            "larceny/theft", "thefts", "burglary/force/res/am", "traff acc", 
            "civil", "alarm - false; chargeable", "theft", "sick case", "felonious assault jh", 
            "intoxicated person", "traffic pursuit", "animal complaint - livability", 
            "juvenile problem", "dui", "traffic stop", "traffic", "auto accident", 
            "traff acc", "[rms] criminal mischief", "traff acc", "burglary", 
            "sidewalk snow & ice complaint", "shots fired", "possess firearm/concealed weapon by convicted felon", 
            "sidewalk structural complaint", "disturbance", "fraud - impersonate", 
            "[ccso]- 10 58 traffic stop", "prostitution loitering", "[003] accident hit and run", 
            "graffiti complaint / reporting", "[hcso]-assault-knife/cutting instrument-spouse", 
            "bomb", "larceny/theft", "theft", "check property", "directed patrol", 
            "disturb", "all other non-traffic crim offenses", "[042] civil", 
            "larceny", "vandalism ($400 or more) (f)", "larceny, tfa", "larceny", 
            "injured person", "burglary", "grand larceny", "found property", 
            "tres", "[cad] domestic", "441", "transport", "traffic signal trouble", 
            "arson", "subject stop", "shooting", "false impr", "business/building check", 
            "property damage accident/pi", "suspicious circ", "admit or e/e", 
            "90z - warrant-ppd cpf", "vehicle disturb", "parking deck", "99a", 
            "disorderly", "remarks", "burglary", "dui", "recovered stolen motor vehicle", 
            "sidewalk snow and ice - ss", "suspicious circ", "graffiti complaint / reporting", 
            "field interview", "medical", "dui alcohol (m)", "burgr", "stln prop", 
            "dui", "unknown problem", "traffic", "cad: suspicious activity", 
            "traff acc", "911/no  voice", "community policing", "drunk in public: alcohol, drugs, combo or toluene (m)", 
            "traff acc", "tamper mv", "found property", "traffic stop", "dui", 
            "stolen vehicle", "larceny, all others", "possession-dangerous drugs-oth", 
            "crim tresp", "[uofm]-cds violation", "traff acc", "sudden death&found bodies", 
            "assault, aggravated", "traffic", "disturbance (knife involved)", 
            "911/no  voice", "malicious destruction i/p", "dui", "burgr", 
            "hit & run", "narcotics i/p", "fraud", "cad: disturbance / disorder", 
            "traffic stop", "larceny", "disorderly", "407", "assist", "cad: suspicious activity", 
            "[rms] burglary commerical business", "panhandler", "954c weapons - illegal", 
            "traff acc", "[cad]-traffic stop", "drug poss", "suspicious subj, veh, or circumstance", 
            "traffic stop", "prkg complaint", "vehicle stop", "welfare check", 
            "shoplifting (m)", "fra crt de", "dui", "assault, domestic bodily injury", 
            "theft of merchandise- $1,000 or less", "animal misc. - canine", 
            "burglary", "abandoned vehicle", "criminal-mischief-other", "s46 - traffic stop", 
            "investigate person", "drug poss", "vehicle-abandoned", "runaway", 
            "parking violation complaint", "assist", "dist the peace", "burglary", 
            "felonious assault ip", "traffic stop", "aggravated assault firearm", 
            "veh recstl", "assaults", "narcotics onview", "pedestrian check", 
            "disturbance", "[rms] hit and run", "threatening", "dui", "23f - theft from motor vehicle", 
            "attempt to locate", "3502", "narcotic / drug law violations", 
            "motor vehicle theft", "pothole", "shots fired ip", "robbery/firearm/hwy/st/alleys", 
            "alarm - hold up/panic", "traffic stop", "traffic", "06057-predpol check", 
            "battery m", "traff acc", "larceny f/auto", "disturb", "burglary", 
            "drug/ narcotic violations", "theft", "non injury hit and run", 
            "proactive police visit", "welfare check - priority", "08* - simple assault", 
            "theft from auto", "traffic stop", "18* - public drunkenness", 
            "private tow", "pd accident", "assault - priority", "- harassment [2450]", 
            "other", "burglary business j/h", "traff acc", "traffic stop", 
            "assault and battery", "agency assist", "investigate", "[cad] accident (no injuries)", 
            "traffic stop", "3921", "forgery", "[hfpd]-medical emergency", 
            "forgery in progress", "[wcso ] citizen assist", "chest pain", 
            "aggravated assault firearm", "emergency", "non injury hit and run", 
            "unknown problem", "bw mis bench warrant misdemeanor", "assist - citizen or agency", 
            "criminal damage graffiti", "investigate person", "550 - fugitive", 
            "sudden death undetermined", "theft/larc/0-50/from mtr veh", 
            "larceny, shoplifting", "abandoned vehicle", "fight", "penalcode", 
            "larceny theft", "identity theft", "assault and battery", "special attention", 
            "grand larc", "dui", "assault", "traffic stop", "exterior nuisance complaint", 
            "vandalism-commercial est", "all other offenses", "burglary business ip", 
            "assault, aggravated", "premise check", "alarm", "robbery-individual", 
            "common assault", "animals-abuse", "larceny", "assault", "traff acc", 
            "burglary in progress", "found property", "silent alarm", "parking violation complaint", 
            "motor vehicle theft", "[ccso]- building, parking lot check", 
            "[cad]-suspicious incident", "residence burglary", "nuisance/obscene calls-literat", 
            "check", "viol order - dv", "[ccso]- 10 35, breaking entering in progress b&e bet", 
            "burglary", "parking violation complaint", "[inc] conservor of peace", 
            "property check", "gta", "assault w/dangerous weapon", "unknown problem", 
            "noise complaint", "larceny", "tavern check", "theft f/auto", 
            "disturbance", "drug/ narcotic violations", "assault & battery spouse/partner", 
            "runaway", "residential conditions complaint", "shots fired", 
            "drug poss", "- theft of license plates", "230f theft from motor vehicle except parts/accessories", 
            "information", "cpp - community policing program", "warrants - outside agency-felo", 
            "traffic stop-si so", "robbery", "traffic", "911/no  voice", 
            "public assist", "petit larc", "rms theft - shoplifting", "criminal trespass     ", 
            "traffic stop", "proactive police visit", "burglary", "family disturb", 
            "dui", "animal complaint - livability", "larceny", "disturbance", 
            "burglary", "traffic stop", "animal complaint - public health", 
            "all other offenses", "udaa report", "dui", "[059] agency assist", 
            "drug poss", "larceny, shoplifting", "miscellaneous complaint", 
            "check property", "hit and run", "traffic stop", "[ccso]- 10 37, suspicious activity", 
            "pc 243 a battery", "theft", "tru - theft", "recovery of reported stolen vehicle", 
            "verified alr / person w/o code", "[ccso]- building, parking lot check", 
            "traffic related calls", "drugs", "assist other department", 
            "[cad]-traffic stop", "traffic stop", "unknown problem", "502e burglary - unlawful entry no force", 
            "motor vehicle theft", "assault and battery", "case: trs - trespass", 
            "traffic complaint", "theft/shoplift", "exterior nuisance complaint", 
            "petit larc", "dui", "probation violation", "vandalism", "animal dead", 
            "larceny", "graffiti complaint / reporting", "telephone, other", 
            "larceny", "traffic stop", "assault -(simple assault)", "runaway", 
            "all other offenses", "drugs", "drug poss", "found property", 
            "[hcso]-property-lost/found/recovered", "parking violation complaint", 
            "other", "miscellaneous traffic", "other assaults", "[cad]-traffic stop", 
            "remarks", "domestic dispute", "xcad doa", "intoxicated subject", 
            "possess controlled substances without a prescription (m)", "cad: suspicious activity", 
            "burglary of vehicle     ", "06* - larceny", "unknown problem", 
            "injured/sick person", "auto accident with injury", "911/no  voice", 
            "exterior nuisance complaint", "dop nrs", "larceny shoplifting over $200", 
            "traffic stop", "unknown problem", "unfounded", "trespass", "all other larceny", 
            "auto x unk inj / impaired", "traffic", "assist", "rms forgery 1", 
            "cad: suspicious activity", "disturbance", "suspicious activity", 
            "cfs-area check n bay island", "suspicious incident", "burglary", 
            "bank check", "assist other", "graffiti", "burglary", "narcotics", 
            "community policing", "[cad]area patrol bus 17b", "35b", "felonious assault ip", 
            "[ccso]- 10 35, patrol check", "misc trouble", "forgery/cntrft - identity theft", 
            "assault and battery", "suspicious circ", "assault and battery", 
            "cad: disturbance / disorder", "agg unlic oper-", "motorist assistance", 
            "veh recstl", "other", "destruct prop", "abandoned vehicle", 
            "towing detail", "traffic accident, non-inj", "larceny theft", 
            "traffic-accident-hit-and-run", "47", "wanted person", "juveniles-outside agency runaw", 
            "grand theft auto", "ra police", "disorderly", "13c - intimidation", 
            "unknown trouble", "911/no  voice", "burglary", "subject stop", 
            "reckless endangerment - dv", "- lost or found prop", "cmc", 
            "n425", "[rms] burglary from auto", "411a", "security check", 
            "cracker barrell", "bleeding", "911 hangup/unk call for service", 
            "fraud", "other", "burg res", "vandalism", "animal disturb", 
            "criminal arrest (warrant) (other agency)", "grand larceny auto", 
            "all other offenses", "ptchp", "disregard traffic control device", 
            "theft, auto", "motor vehicle acc pro dam", "other", "all other offenses", 
            "misc trouble", "petty theft", "federal way warrants", "animal complaint - livability", 
            "all other offenses", "premise check", "traffic stop", "common assault", 
            "special attention", "burglary/no frc/res/am", "traffic violation", 
            "found property", "narcoticsoutside", "assist ecso", "ptchp", 
            "larceny", "private tow", "39r", "disturbance", "burglar alarm", 
            "accident - minor", "cad: assault", "citesign", "disturbance - priority", 
            "dop nrs", "larceny - other offenses", "vehicle stop", "traffic stop", 
            "assault", "[cad]-juvenile complaint", "[ccso]- 10 16, assault domestic", 
            "financial card fraud", "larceny/theft from motor vehicle", "rms: autos/stolen local", 
            "theft of vehicle", "cad: criminal trespass", "tru - theft", 
            "dui", "dip - disorderly person", "felonious assault ip", "traff acc", 
            "550 - trespassing", "[cpd]-traffic stop", "cad: disturbance / disorder", 
            "fire:  cut off gas", "all other offenses", "other assaults", 
            "dui", "theft", "[cad]-traffic stop", "larceny", "special attention", 
            "auto x unk inj / impaired", "burglary", "drug arrest", "larceny", 
            "burglary of building", "dui", "unauthorized use of vehicle", 
            "unknown trouble", "vicious animal", "auto theft", "leaving the scene", 
            "11-95", "[rms] assault", "special attention", "dui", "security check - 9550", 
            "emergency", "petit larc", "trbl w/subj", "found property", "animal complaint", 
            "child /  adult abuse", "driving under the influence", "commercial vehicle enforcement", 
            "silent alarm", "drug arrest", "cpp - community policing program", 
            "traffic stop", "traffic stop", "hit and run", "[ccso]- 10 35, patrol check", 
            "99a", "burglary/force/non res/unk", "disorderly", "disorderly", 
            "special attention", "aggravated assault", "assault a", "person contact (86)", 
            "dop nrs", "burglary", "assault, aggravated", "welfare check senior program", 
            "hit and run", "theft", "auto x or ped x - injuries", "damage to property", 
            "[wlpd] ala  (alarm,audible)", "criminal misc pd", "driving while license suspended", 
            "1154", "citizen assist", "cad: suspicious activity", "larceny", 
            "4101", "burglary occupied resd i/p", "[cad] warrant", "property crime", 
            "lost property", "directed patrol", "rape", "larceny", "narcotic / drug law violations", 
            "lpd-check on welfar", "exterior nuisance complaint", "assault w/injury-fam/date viol     ", 
            "udaa report", "- suspicion", "all other offenses", "911/no  voice", 
            "runaway", "drugs", "270 - non-criminal offense/domestic disturbance", 
            "assault simple, not aggravated", "investigate person", "car jacking", 
            "burgc", "threats report", "recovered stolen motor vehicle", 
            "assault/simple", "larceny from auto over $200", "traffic accident", 
            "disturbance other", "other assaults", "theft-grand", "other offense", 
            "larceny bicycle $50 - $199", "burglary", "aggravated assault", 
            "return for additional info", "domestic", "special attention", 
            "theft of vehicle", "drug poss", "theft-prsnatch", "larceny", 
            "felonious assault ip", "false alarm", "weapon violations", "traffic related calls", 
            "4002", "vandalism, schools, public(old", "cad: disturbance / disorder", 
            "speeding radar", "admit or e/e", "disorderly", "gta", "pothole", 
            "exterior nuisance complaint", "narcotics i/p", "residential conditions complaint tenant", 
            "motor vehicle theft", "441", "animal related", "auto burglary", 
            "assist other", "traffic stop", "disorderly and/or inebriated", 
            "drug poss", "traffic", "cad: suspicious activity", "sale/mfg-marijuana", 
            "abandoned vehicle", "dog bite", "assault and battery", "traff acc", 
            "suspicious circ", "[ccso]- 10 58 traffic stop", "petty theft(from veh) (m)", 
            "veh recstl", "[ccso]- building, parking lot check", "investigate", 
            "proactive police visit", "burglar alarm", "[cad]-traffic stop", 
            "disturbances", "narcoticsoutside", "community policing", "follow up", 
            "larceny", "check property", "theft petit -  other", "vandalism", 
            "burg no force - res/day", "possess narcotic controlled substance [35a]", 
            "[rms] burglary of vehicle", "citizen assist", "baker act", "larceny, s/l", 
            "dop nrs", "fire:  82 accident w/inj", "larceny report", "murder", 
            "felonious assault ip", "theft", "larceny", "3921", "5503(a)(1)", 
            "alarm", "burglary of residence 2nd deg", "alc - alarm commercial", 
            "dui", "[ccso]- building, parking lot check", "fraud, all others", 
            "[rms] sexual assault other (adult)", "assault and battery", 
            "larceny theft", "family disturb", "domestic", "[ccso]- 10 35, fireworks", 
            "larceny", "rms: under $50 theft/from auto", "burglary non residence     ", 
            "assault-simple", "warrant (aransas county)", "assault and battery", 
            "intoxication", "traffic accident", "simple assault-family", 
            "miss pers", "traffic stop", "unknown trouble", "drug arrest", 
            "pothole", "cad: disturbance / disorder", "od - overdose", "theft cl c shoplifting", 
            "415", "direct traffic", "investigate person", "[ccso]- building, parking lot check", 
            "careless negligent motor veh", "sewer issues", "larceny", "family disturbance", 
            "investigate person", "welfare check", "theft-pkpocket", "larceny", 
            "viol order - dv", "agg asslt firearm citizen", "panhandling", 
            "911/no  voice", "aided case", "traffic stop", "misc report", 
            "peace order", "416b", "exterior nuisance complaint", "other", 
            "gta", "community policing", "cpp - community policing program", 
            "animal complaint - livability", "exterior nuisance complaint", 
            "misc trouble", "signal 3", "other assaults", "ts", "grand larceny", 
            "transport", "- domestic disturbances [3600]", "found property", 
            "found property", "assault, aggravated", "weapon laws", "community policing", 
            "larceny f/auto", "community policing", "graffiti complaint / reporting", 
            "pothole", "vc 10851 vehicle theft", "dui", "traff acc", "criminal mischief (felony)", 
            "dip - disorderly person", "welfare check - cold", "felonious assault ip", 
            "robbery-individual", "drug poss", "gta", "vehicle stop", "larceny all other", 
            "check person", "vandalism/criminal mischief", "drug poss", "follow up", 
            "graffiti complaint / reporting", "animal complaints", "ra police", 
            "aggravated assault", "dui", "noise complaint", "graffiti complaint / reporting", 
            "13a - aggravated assault", "directed patrol", "other assaults", 
            "felonious assault ip", "drug possession", "larceny", "criminal trespass notice     ", 
            "23h-all other larceny", "hit and run", "community policing", 
            "alarm", "burglary occupant away i/p", "assault", "auto x or ped x - injuries", 
            "burglary", "accident - hit & run - priority", "life status questionable delta", 
            "dui", "runaway", "[012] reckless driver", "foot  patrol", "fingerprinting", 
            "criminal damage", "abandoned vehicle", "field interview", "911/no  voice", 
            "theft vehicle", "larceny", "indecent-exposure", "war - warrant", 
            "misc disturbance", "[ccso]- building, parking lot check", "animal", 
            "traffic", "animal complaint - livability", "traff acc", "alarm", 
            "accident - injury", "area check", "larceny", "suspicious person", 
            "disturbance family", "auto accident", "traff acc", "traffic", 
            "larceny", "larceny / theft offenses - theft from motor vehicle", 
            "traffic-accident", "dui", "disturbance", "special attention", 
            "veh recstl", "take vehicle w/o owner's consent/vehicle theft", 
            "disturbance", "drug poss", "larceny", "auto x unk inj / impaired", 
            "[rms] theft - grand and larceny", "911/no  voice", "vandalism & crim mischief", 
            "larceny from building over $200", "suspicious subj, veh, or circumstance", 
            "7200 motor vehic theft-truck/bus", "[ccso]- building, parking lot check", 
            "larceny theft", "veh recovery for osa", "larceny", "[cad]-suspicious incident", 
            "theft - priority", "liquor - unlawful poss under 21", "misc report", 
            "alarm burglar", "drug arrest", "s46 - traffic stop", "simple assault - dv", 
            "fall with injury", "criminal damage", "accident no inj", "cutting", 
            "[ccso]- 10 35, destruction of property dop, in progress", "disturbance", 
            "spousal abuse - aggravated assault", "bomb", "cad: assault", 
            "disorder", "[056] arrest", "robbery", "hazard - hazardous condition", 
            "missing report", "dop nrs", "shoplifting", "sex-aslt-non-rape", 
            "crash / accident", "fire", "drug arrest", "petit larceny by shoplifting", 
            "vehicle tow", "911/no  voice", "found property", "theft of vehicle", 
            "301 - rape/sexual assault vic 15 yr and younger", "public assist check welfare", 
            "runaway", "pothole", "batt polic", "parking violation complaint", 
            "parking violation complaint", "[ccso]- building, parking lot check", 
            "accident - unknown injury", "traffic misc so", "animal complaint - livability", 
            "traffic related calls", "[cad] alarm - general 7393", "traffic stop", 
            "traff acc", "directed patrol", "domestic", "rms runaway", "citizen assist", 
            "malicious destruction rpt", "drug poss", "simple assault", "cad: suspicious activity", 
            "[cad]-traffic stop", "miscellaneous traffic", "recover auto", 
            "[ccso]- 10 16, assault in progress, domestic", "use of stolen identity to obtain goods/svc [pc 530.5]", 
            "domestic dispute", "hit & run", "loud music", "dui", "gta", 
            "recover auto", "crim misch cl btheft cl b other", "theft-carprowl", 
            "traffic stop-si ro", "traffic-accident-hit-and-run", "burglary/force/res/am", 
            "burgr", "4 accident", "breaking & entering auto rpt", "traffic stop", 
            "47", "dui", "traffic stop", "common assault", "narcotics i/p", 
            "1090c", "auto theft", "burglar alarm, silent", "unknown problem", 
            "vehicle accident", "towing detail", "hit and run", "foot patrol", 
            "special attention", "intentional vandalism", "cad: traffic complaint", 
            "fugitive attachment", "silent alarm", "[wlpd] ord  (ordinance violation)", 
            "larceny", "aband veh", "[hcso]-vandalism mal dest/mv", "extra patrol - business", 
            "alarm", "burglary occupant away j/h", "traffic", "penalcode", 
            "rms: under $50 theft/from auto", "cad: traffic complaint", "416b", 
            "follow up", "5507(a)", "drug poss", "trespass", "traffic accident", 
            "other assaults", "assault a", "larceny", "fraud offenses - credit card / automated teller machin", 
            "larceny", "larceny theft", "all other offense", "juv neglected/abused - dv", 
            "[inc] 23d theft from building", "auto x or ped x - injuries", 
            "poss drugs", "domestic standby", "miscellaneous", "recover auto", 
            "pothole", "traffic stop", "fireworks complaint", "traff acc", 
            "auto x hit& run unk injuries", "[ccso]- building, parking lot check", 
            "assault a", "loud party or noise", "missing lost person", "larceny", 
            "larceny", "dop nrs", "911/no  voice", "3303", "business check", 
            "suspicious - priority", "special attention", "assault", "complaint other", 
            "careless driving", "burglary", "dui", "vehicle code violation", 
            "family problem-no violence", "resisting arrest", "traffic", 
            "threat/terrorizing", "[lcpd] alarm,intru", "911/no  voice", 
            "assault, aggravated", "probation violation", "dui", "special attention", 
            "petit larc", "[wlpd] aoa  (assist outside agency)", "non-aggravated assaults", 
            "protective order", "traffic stop", "bus boarding", "traff acc", 
            "cad: suspicious activity", "larceny", "fraud credit card/automated teller machines", 
            "larceny", "drug poss", "motor vehicle collision investigation", 
            "[ccso]- building, parking lot check", "complaint other", "family disturbance em", 
            "burglary/breaking & entering", "police info", "false burglar alarm", 
            "[spd]-grand theft", "traffic", "disturbance-oth", "sewer issues", 
            "larceny", "violate restraining order", "traffic accident minor", 
            "larceny", "disturbance", "udaa report", "s18 - suspicious", 
            "traffic stop", "abandoned vehicle", "drug poss", "traffic stop", 
            "traffic stop", "suspicious circ", "sudden death natural", "harassment by physical contact  or attempts or threats", 
            "transport prisoner", "special attention", "non-injury accident", 
            "gone on arrival", "identity theft", "criminal mischief", "dui", 
            "13(a)(16)", "bus boarding", "burglary/ b & e, residential", 
            "larc-from motor veh", "special attention", "auto x or ped x - injuries", 
            "disturbance", "abandoned vehicle", "dui", "551 - criminal damaging", 
            "drug poss", "residential conditions complaint tenant", "hit and run", 
            "animal misc/recheck", "traff acc", "fireworks", "holding person", 
            "3921", "260 - discharged firearms - occupied structure", "information", 
            "inci: nop - nbrhd oriented policing", "assault", "traff acc", 
            "community policing", "burglary", "crash/leaving the scene     ", 
            "abandoned vehicle", "larceny", "parking violation complaint", 
            "request officer", "private tow", "unknown problem", "found property     ", 
            "trf-hitrun", "animal complaint - public health", "nat community assis", 
            "petit larc", "driving under the influence", "06055-extra patrol check", 
            "0045 assault-hand/fist/feet-gm", "burglary/force/non res/pm", 
            "public drunkeness", "vandalism", "traffic", "narcoticsoutside", 
            "grand theft auto", "theft, auto", "assault and battery", "breaking and entering", 
            "property damage accident", "suspicious person/circumstance", 
            "rms drugs-poss-small amt-marijuana in mv", "drug poss", "[rppd]-traffic accident - pi", 
            "traffic", "juv", "661 - assist - public/extra patrol", "auto x unk inj / impaired", 
            "cad: theft", "t", "sv", "traff acc", "assault and battery", 
            "found drugs", "hit and run", "larceny", "disorderly", "unknown problem", 
            "robbery armed jh-any weapon", "vicious animal", "disturbance - priority", 
            "larceny i/p or j/h", "repairs/service", "hazard - hazardous condition", 
            "vehicle check", "traffic", "drug arrest", "theft of vehicle", 
            "repo", "off public intoxication", "[hcso]-assault-simple-spouse", 
            "other assaults", "[rms] stolen vehicles", "tfmv", "disorderly", 
            "destruct prop", "motor vehicle theft", "tstop", "trespassing", 
            "non specific diag or illness", "trespass", "animal complaint - livability", 
            "dui", "common assault", "traffic stop", "larceny", "traffic stop", 
            "[cad]-abandoned vehicle", "trespass", "family disturb", "larceny", 
            "malicious destruction rpt", "suspicious circ", "drugs", "assault c", 
            "54a p-mv abandoned", "[rms] larc-shoplift", "cad: suspicious activity", 
            "23152", "lewd and lascivious ip", "towing detail", "assault and battery", 
            "destruction of property, private property", "traff acc", "towing detail", 
            "5203", "traffic-accident", "driving- revoked license", "poss contrl sub paraphernalia", 
            "keep the peace", "vehicle stop", "[ccso]- 10 35, patrol check", 
            "drugs", "rms: autos/stolen local", "[cad] police", "harassment - dv", 
            "auto burglary", "suicide", "driving under influence", "wanted on warr", 
            "disturbance", "mental transport", "traffic", "exterior nuisance complaint", 
            "traffic", "disorderly", "- larceny-shoplifting", "051 - burglary - residence", 
            "traffic stop", "auto x or ped x - injuries", "drug arrest", 
            "abandoned vehicle", "traffic stop", "larceny shoplifting $50 - $199", 
            "parking violation complaint", "threats report", "cad: traffic enforcement", 
            "burglary", "dui", "cad: weapons offenses", "inci: traffic stop", 
            "assault, aggravated", "[034] trespass", "36 - animal complaint", 
            "overdose", "asn - assignment", "threats", "larceny", "common assault", 
            "tpot - theft, property, other", "found drugs", "theft-items-from-vehicle", 
            "panic / duress alarm", "suspicious vehicle", "parking complaint", 
            "proactive police visit", "special attention", "directed patrol", 
            "warrant service", "3702", "civil standby", "dui", "common assault", 
            "[cad]-traffic stop", "[sspd] accident", "auto accident", "theft from auto", 
            "petit larceny: theft from motor vehicle", "934d incidents - suspicious", 
            "dui", "[lpd]-assault - just occurred", "acc - accident property damage", 
            "[rms] juvenile runaways", "drug law violations", "susp person", 
            "criminal damaging/endangering", "drug poss", "trf-hitrun", "gta", 
            "drug law violations", "dui", "406", "auto accident", "recover auto", 
            "other", "community policing", "trespass", "theft, prop, othr", 
            "motor vehicle theft", "traffic hazard", "one down or over the wheel", 
            "traff acc", "special attention", "missing person", "welfare check - priority", 
            "security check", "drug poss", "larceny report", "larceny", "runaway", 
            "sewer issues", "fraud", "traffic", "threats", "dui", "traffic incident", 
            "new call", "other assaults", "silent alarm", "traffic", "disorderly", 
            "911/no  voice", "traffic stop", "drugs", "other", "motor vehicle theft/auto", 
            "vandalism", "burglary", "traffic stop", "special attention", 
            "dop nrs", "fire - all other", "abandoned vehicle", "investigate person", 
            "30b", "traff acc", "traffic hazard", "disturbance (other)", 
            "dui", "traffic related", "assist public", "dui", "911/no  voice", 
            "disorderly", "abandoned vehicle", "assault, aggravated", "motor vehicle theft", 
            "suspicious person", "[lcpd] traffic control", "911/no  voice", 
            "701a motor veh theft & recover - autos", "[wpd]-al other traffic violations", 
            "investigate person", "911 hang up", "54e p-traffic / parking complaints", 
            "alarm", "[cad]-burglar alarm", "90d driving under the influance", 
            "community policing", "burglary", "check well being", "traffic stop", 
            "warr stop with release", "traffic-accident", "holding person", 
            "cad: non-injury accident", "disturbance", "hit and run", "gta", 
            "theft by unlawful taking or disposition.", "arson-uninhabited-other resid", 
            "traff acc", "aided case", "general assistance (escorts, service calls)", 
            "malicious destruction i/p", "[rms] traf-free txt", "assault by threat     ", 
            "recovered stolen vehicle recovered stolen vehicle", "battery a", 
            "felonious assault ip", "unfounded", "dui", "utility problem", 
            "misc. public service", "graffiti complaint / reporting", "felonious assault ip", 
            "drug poss", "burglary construction - non-forced entry", "cad: suspicious activity", 
            "one down or over the wheel", "burgv", "xcad warrant service", 
            "traffic stop", "traff acc", "crim misch", "drugs", "traffic", 
            "petit larc", "found property", "911/no  voice", "23c shoplifting", 
            "theft by unlawful taking or disposition.", "towing detail", 
            "suspicious pers", "larceny", "community policing", "trespass warning", 
            "community policing", "parking violation complaint", "possess a controlled dangerous substance - schedule i", 
            "theft/larceny-200/over", "larceny", "theft/other", "towing detail", 
            "traffic", "traffic", "911/no  voice", "xcad traffic stop", "foot patrol", 
            "following to closely", "other assaults", "animal complaint - public health", 
            "burglary", "fraud", "disturbance", "pc 594 vandalism", "agg assault", 
            "sell/furnish/give/transport/etc marijuana", "hit and run", "nat theft", 
            "theft/larceny", "motor vehicle theft", "obstructing", "auto accident", 
            "breaking & entering", "cps referral", "larceny", "[ccso]- building, parking lot check", 
            "medical call", "auto x or ped x - injuries", "community policing", 
            "patrol check", "liquor", "traffic incident", "fraud", "alarm", 
            "47", "thefts", "traffic stop", "unwanted person", "hit and run", 
            "disorderly", "public intox", "disturbance")