---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    includes:
      - after_body: include_twitter.html
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

???

Image credit: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Sharingan_triple.svg)

---

<blockquote class="twitter-tweet" data-lang="fr"><p lang="fr" dir="ltr">Il y a pas la pp :/<br>Yep, j&#39;avais noté ;) <a href="https://t.co/FdkwUX2ess">pic.twitter.com/FdkwUX2ess</a></p>&mdash; Bichaton 📊 (@_AntoineB) <a href="https://twitter.com/_AntoineB/status/930728129114591232?ref_src=twsrc%5Etfw">15 novembre 2017</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


---

```{r, comment="", warning=FALSE}
available::available("bigstatsr", browse = FALSE)
```


---

class: center, middle

# Thanks!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

The chakra comes from [remark.js](https://remarkjs.com), [**knitr**](http://yihui.name/knitr), and [R Markdown](https://rmarkdown.rstudio.com).
